In [11]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
from sklearn.datasets import make_regression

In [13]:
x, y = make_regression(n_samples=30, n_features=2, noise=1, random_state=42)
x, y

(array([[-0.29169375, -0.60063869],
        [ 1.52302986,  0.64768854],
        [-0.3011037 , -0.11564828],
        [ 0.76743473,  1.57921282],
        [-1.42474819,  0.0675282 ],
        [-1.22084365,  0.82254491],
        [ 1.85227818, -0.60170661],
        [-1.95967012,  0.2088636 ],
        [-1.05771093, -0.01349722],
        [-1.4123037 , -0.90802408],
        [-0.30921238, -0.83921752],
        [ 1.05712223, -0.46063877],
        [ 0.54256004, -0.46947439],
        [ 0.37569802, -1.15099358],
        [ 0.17136828,  0.73846658],
        [-0.2257763 ,  1.46564877],
        [-0.56228753, -1.72491783],
        [-0.46572975, -0.46341769],
        [ 0.97554513,  0.33126343],
        [-0.23413696, -0.23415337],
        [ 0.31424733, -1.01283112],
        [ 0.11092259, -0.54438272],
        [ 0.19686124, -1.32818605],
        [ 0.61167629, -0.676922  ],
        [-0.1382643 ,  0.49671415],
        [-1.91328024,  0.24196227],
        [-1.76304016,  0.34361829],
        [ 0.93128012,  1.030

In [14]:
# Normalization
x = (x - np.min(x)) / (np.max(x) - np.min(x))

In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.1, random_state=42)
(x_train.shape, y_train.shape), (x_test.shape, y_test.shape)

(((27, 2), (27,)), ((3, 2), (3,)))

In [16]:
class LinearRegressionClassifier:
    def __init__(self, lr=0.01, n_iters=100):
        self.lr = lr
        self.n_iters = n_iters
    

    def fit(self, x, y):
        if len(x.shape) == 1:
            self.n_params = 1
        else:
            self.n_params = x.shape[1]
        
        sample_size = x.shape[0]

        self.bias = 0.0
        self.params = np.random.uniform(low=0.5, high=1.5, size=self.n_params)


        for _ in range(self.n_iters):
            for i in range(sample_size):
                y_pred = np.dot(x[i], self.params.T) + self.bias
                for j in range(self.n_params):
                    self.params[j] -= self.lr * (y_pred - y[i]) * x[i][j]
                self.bias -= self.lr * (y_pred - y[i])
    


    def predict(self, x):
        return np.dot(x, self.params.T) + self.bias


In [17]:
clf = LinearRegressionClassifier(lr=0.01, n_iters=1000)
clf.fit(x_train, y_train)

In [18]:
clf.predict(x_test), y_test

(array([ 40.13549223,  47.36840852, -18.5807736 ]),
 array([ 40.5479008 ,  47.02720532, -19.04126191]))