In [67]:
import warnings
warnings.filterwarnings('ignore') # to ignore warnings about pandas library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import accuracy_score

In [68]:
class LogisticRegressionClassifier:
    def __init__(self, lr=0.01, n_iters=100):
        self.lr = lr
        self.n_iters=n_iters
    

    def fit(self, x, y):
        if len(x.shape) == 1:
            self.n_params = 1
        else:
            self.n_params = x.shape[1]
        
        sample_size = x.shape[0]

        self.params = np.random.uniform(low=0.5, high=1.5, size=self.n_params)
        self.bias = 0.0

        epsilon = 1e-5
        for _ in range(self.n_iters):

            for i in range(sample_size):
                z = np.dot(x[i], self.params.T) + self.bias
                y_pred = 1 / (1 + np.exp(-z))

                for j in range(self.n_params):
                    self.params[j] -= self.lr * ( ((1-y[i])/(1-y_pred+epsilon)) - (y[i]/y_pred+epsilon) )  *  ( np.exp(-z) / np.square(1 + np.exp(-z)) ) * x[i][j]

                self.bias -= self.lr * ( ((1-y[i])/(1-y_pred+epsilon)) - (y[i]/y_pred+epsilon) )  *  ( np.exp(-z) / np.square(1 + np.exp(-z)) )
        

    def predict(self, x):
        z = np.dot(x, self.params.T) + self.bias
        return 1 / (1 + np.exp(-z))
    

    def score(self, x, y):
        y_pred = self.predict(x)
        y_pred = [1 if i > 0.5 else 0 for i in y_pred]
        return accuracy_score(y_pred=y_pred, y_true=y)



In [69]:
x = np.array([3.78, 2.44, 2.09, 0.14, 1.72, 1.65, 4.92, 4.37, 4.96, 4.52, 3.69, 5.88]).reshape(-1,1)
y = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1])
x, y

(array([[3.78],
        [2.44],
        [2.09],
        [0.14],
        [1.72],
        [1.65],
        [4.92],
        [4.37],
        [4.96],
        [4.52],
        [3.69],
        [5.88]]),
 array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1]))

In [70]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42, stratify=y)

In [71]:
clf = LogisticRegressionClassifier()
clf.fit(x_train, y_train)

In [72]:
clf.score(x_test, y_test)

1.0

In [73]:
y_pred = clf.predict(x_test)
y_pred

array([0.63818701, 0.8234561 , 0.26721071, 0.42378729])

In [74]:
y_pred = [1 if i > 0.5 else 0 for i in y_pred]
y_pred, y_test

([1, 1, 0, 0], array([1, 1, 0, 0]))

In [76]:
clf.score(x_train, y_train)

0.75

In [77]:
clf.score(x_test, y_test)

1.0